parameters:
    ngmore.listener.user.class: Netgen\Bundle\MoreBundle\EventListener\UserEventListener
    ngmore.listener.user.post_register.class: Netgen\Bundle\MoreBundle\EventListener\User\PostRegisterEventListener
    ngmore.listener.user.activation_request.class: Netgen\Bundle\MoreBundle\EventListener\User\ActivationRequestEventListener
    ngmore.listener.user.post_activate.class: Netgen\Bundle\MoreBundle\EventListener\User\PostActivateEventListener
    ngmore.listener.user.password_reset_request.class: Netgen\Bundle\MoreBundle\EventListener\User\PasswordResetRequestEventListener
    ngmore.listener.user.post_password_reset.class: Netgen\Bundle\MoreBundle\EventListener\User\PostPasswordResetEventListener

services:
    ngmore.listener.user:
        abstract: true
        class: %ngmore.listener.user.class%
        arguments:
            - @ngmore.helper.mail_helper
            - @ezpublish.config.resolver
            - @ngmore.repository.nguser_setting
            - @ngmore.repository.ezuser_accountkey

    ngmore.listener.user.post_register:
        class: %ngmore.listener.user.post_register.class%
        parent: ngmore.listener.user
        tags:
            - { name: kernel.event_listener, event: ngmore.events.user.post_register, method: onUserRegistered }

    ngmore.listener.user.activation_request:
        class: %ngmore.listener.user.activation_request.class%
        parent: ngmore.listener.user
        tags:
            - { name: kernel.event_listener, event: ngmore.events.user.activation_request, method: onActivationRequest }

    ngmore.listener.user.post_activate:
        class: %ngmore.listener.user.post_activate.class%
        parent: ngmore.listener.user
        tags:
            - { name: kernel.event_listener, event: ngmore.events.user.post_activate, method: onPostActivate }

    ngmore.listener.user.password_reset_request:
        class: %ngmore.listener.user.password_reset_request.class%
        parent: ngmore.listener.user
        tags:
            - { name: kernel.event_listener, event: ngmore.events.user.password_reset_request, method: onPasswordResetRequest }

    ngmore.listener.user.post_password_reset:
        class: %ngmore.listener.user.post_password_reset.class%
        parent: ngmore.listener.user
        tags:
            - { name: kernel.event_listener, event: ngmore.events.user.post_password_reset, method: onPasswordReset }
