parameters:
    ezpublish.fieldType.childrenindexer.class: %ezpublish.fieldType.eznull.class%
    ezpublish.fieldType.childrenindexer.converter.class: eZ\Publish\Core\Persistence\Legacy\Content\FieldValue\Converter\Null

services:
    ezpublish.fieldType.childrenindexer:
        class: %ezpublish.fieldType.childrenindexer.class%
        parent: ezpublish.fieldType
        arguments: [ "childrenindexer" ]
        tags:
            - {name: ezpublish.fieldType, alias: childrenindexer}

    ezpublish.fieldType.childrenindexer.converter:
        class: %ezpublish.fieldType.childrenindexer.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: childrenindexer, lazy: true, callback: '::create'}
