parameters:
    ezpublish.fieldType.childrenindexer.class: %ezpublish.fieldType.eznull.class%

services:
    ezpublish.fieldType.childrenindexer:
        class: %ezpublish.fieldType.childrenindexer.class%
        parent: ezpublish.fieldType
        tags:
            - {name: ezpublish.fieldType, alias: childrenindexer}
