parameters:
    netgen_more.field_type.childrenindexer.class: %ezpublish.fieldType.eznull.class%
    netgen_more.field_type.childrenindexer.converter.class: %ezpublish.fieldType.eznull.converter.class%

services:
    netgen_more.field_type.childrenindexer:
        class: %netgen_more.field_type.childrenindexer.class%
        parent: ezpublish.fieldType
        arguments: [ 'childrenindexer' ]
        tags:
            - {name: ezpublish.fieldType, alias: childrenindexer}

    netgen_more.field_type.childrenindexer.converter:
        class: %netgen_more.field_type.childrenindexer.converter.class%
        tags:
            - {name: ezpublish.storageEngine.legacy.converter, alias: childrenindexer, lazy: true, callback: '::create'}
