parameters:
    ngmore.field_type.ezxmltext.converter.direct_download.class: Netgen\Bundle\MoreBundle\XmlText\Converter\EzLinkDirectDownload

services:
    ngmore.field_type.ezxmltext.converter.direct_download:
        class: "%ngmore.field_type.ezxmltext.converter.direct_download.class%"
        arguments:
            - "@netgen.ezplatform_site.load_service"
            - "@router"
            - "@?logger"
        tags:
            - { name: ezpublish.ezxml.converter }
