parameters:
    ngmore.field_type.ezxmltext.converter.direct_download.class: Netgen\Bundle\MoreBundle\XmlText\Converter\EzLinkDirectDownload

services:
    ngmore.field_type.ezxmltext.converter.direct_download:
        class: %ngmore.field_type.ezxmltext.converter.direct_download.class%
        arguments:
            - "@ezpublish.api.service.location"
            - "@ezpublish.api.service.content"
            - "@router"
            - "@ezpublish.translation_helper"
            - "@ezpublish.field_helper"
            - "@?logger"
        tags:
            - { name: ezpublish.ezxml.converter }
