parameters:
    ezpublish.image_alias.imagine.cache_resolver.class: Netgen\Bundle\MoreBundle\Imagine\IORepositoryResolver

services:
    ezpublish.image_alias.variation_purger:
        alias: ezpublish.image_alias.variation_purger.legacy_storage_image_file

    ezpublish.image_alias.variation_path_generator:
        alias: ezpublish.image_alias.variation_path_generator.original_directory

    # Implemented to avoid issues with config resolver on Symfony 2.8
    # See https://github.com/ezsystems/ezpublish-kernel/pull/1666
    ezpublish.cache_warmer.config_resolver_cleanup:
        class: Netgen\Bundle\MoreBundle\Cache\Warmer\ConfigResolverCleanup
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: kernel.cache_warmer }

    # Disable original Twig cache warmer to avoid issues on Symfony 2.8
    twig.template_cache_warmer:
        synthetic: true
