parameters:
    ezpublish.controller.page.view.class: Netgen\Bundle\MoreBundle\Controller\PageController

    ezpublish.fieldType.ezobjectrelationlist.class: Netgen\Bundle\MoreBundle\Core\FieldType\RelationList\Type
    ezpublish.fieldType.ezobjectrelationlist.converter.class: Netgen\Bundle\MoreBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\RelationListConverter

    ezpublish.controller.content.view.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Controller\Content\ViewController
    ezpublish.image_alias.imagine.cache_resolver.class: Netgen\Bundle\MoreBundle\Imagine\IORepositoryResolver

    # Override to enable mulitbyte url alias to work correctly (fixed in EZP v6)
    # https://github.com/ezsystems/ezpublish-kernel/pull/1394
    ezpublish.spi.persistence.legacy.url_alias.handler.class: Netgen\Bundle\MoreBundle\Core\Persistence\Legacy\Content\UrlAlias\Handler

    # Override to fix a bug where repository sudo method does not use signal slot repo
    # https://github.com/ezsystems/ezpublish-kernel/pull/1393
    ezpublish.signalslot.repository.class: Netgen\Bundle\MoreBundle\Core\SignalSlot\Repository
    ezpublish.api.inner_repository.class: Netgen\Bundle\MoreBundle\Core\Repository\Repository

    # Override to enable quality and jpeg_quality settings in liip_imagine configuration root
    # https://github.com/ezsystems/ezpublish-kernel/pull/1232
    liip_imagine.filter.configuration.class: Netgen\Bundle\MoreBundle\Imagine\Filter\FilterConfiguration

    # Override to throw Symfony's NotFoundHttpException on 404 response from Legacy Stack
    # See https://netgen.atlassian.net/browse/NGMOREPL-85
    ezpublish_legacy.response_manager.class: Netgen\Bundle\MoreBundle\LegacyResponse\LegacyResponseManager
