services:
    ngmore.layouts.block.plugin.vertical_whitespace:
        class: Netgen\Bundle\MoreBundle\Layouts\Block\Plugin\VerticalWhitespacePlugin
        public: false
        tags:
            - { name: netgen_block_manager.block.block_definition_handler.plugin, priority: 10 }

    ngmore.layouts.block.plugin.background_image:
        class: Netgen\Bundle\MoreBundle\Layouts\Block\Plugin\BackgroundImagePlugin
        public: false
        arguments:
            - "@netgen.ezplatform_site.load_service"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler.plugin, priority: 10 }
