services:
    ngmore.layouts.block.plugin.vertical_whitespace:
        class: Netgen\Bundle\MoreBundle\Layouts\Block\Plugin\VerticalWhitespacePlugin
        public: false
        tags:
            - { name: netgen_block_manager.block.block_definition_handler.plugin, priority: 10 }
