parameters:
    ngmore.matcher.config_resolver.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ConfigResolverBased
    ngmore.matcher.content.content_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\Content
    ngmore.matcher.content.content_type_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\ContentType
    ngmore.matcher.content.content_type_group_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\ContentTypeGroup
    ngmore.matcher.content.location_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\Location
    ngmore.matcher.content.parent_content_type_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\ParentContentType
    ngmore.matcher.content.parent_location_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\ParentLocation
    ngmore.matcher.content.remote_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\Remote
    ngmore.matcher.content.location_remote_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\LocationRemote
    ngmore.matcher.content.section_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\Section

services:
    ngmore.matcher.config_resolver:
        class: "%ngmore.matcher.config_resolver.class%"
        abstract: true
        arguments: ["@ezpublish.config.resolver"]

    ngmore.matcher.content.content_id:
        class: "%ngmore.matcher.content.content_id.class%"
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.content.content_type_id:
        class: "%ngmore.matcher.content.content_type_id.class%"
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.content.content_type_group_id:
        class: "%ngmore.matcher.content.content_type_group_id.class%"
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.content.location_id:
        class: "%ngmore.matcher.content.location_id.class%"
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.content.parent_content_type_id:
        class: "%ngmore.matcher.content.parent_content_type_id.class%"
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.content.parent_location_id:
        class: "%ngmore.matcher.content.parent_location_id.class%"
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.content.remote_id:
        class: "%ngmore.matcher.content.remote_id.class%"
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.content.location_remote_id:
        class: "%ngmore.matcher.content.location_remote_id.class%"
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.content.section_id:
        class: "%ngmore.matcher.content.section_id.class%"
        parent: ngmore.matcher.config_resolver
