parameters:
    ngmore.menu.relation_list_menu_builder.class: Netgen\Bundle\MoreBundle\Menu\RelationListMenuBuilder

services:
    ngmore.menu.relation_list_menu_builder:
        class: %ngmore.menu.relation_list_menu_builder.class%
        arguments:
            - @knp_menu.factory
            - @ezpublish.api.repository
            - @ezpublish.field_helper
            - @ezpublish.translation_helper
            - @ngmore.helper.site_info_helper
            - @ngmore.helper.sort_clause_helper
            - @router
            - @?logger

    ngmore.menu.main_menu:
        class: Knp\Menu\MenuItem
        factory: [@ngmore.menu.relation_list_menu_builder, createRelationListMenu]
        arguments:
            - main_menu
        tags:
            - { name: knp_menu.menu, alias: ngmore_main_menu }

    ngmore.menu.additional_menu:
        class: Knp\Menu\MenuItem
        factory: [@ngmore.menu.relation_list_menu_builder, createRelationListMenu]
        arguments:
            - additional_menu
        tags:
            - { name: knp_menu.menu, alias: ngmore_additional_menu }
