services:
    ngmore.menu.relation_list_menu_builder:
        class: Netgen\Bundle\MoreBundle\Menu\RelationListMenuBuilder
        public: false
        arguments:
            - "@knp_menu.factory"
            - "@netgen.ezplatform_site.load_service"
            - "@netgen.ezplatform_site.filter_service"
            - "@ngmore.helper.site_info_helper"
            - "@ngmore.helper.sort_clause_helper"
            - "@router"
            - "@?logger"
        tags:
            - { name: monolog.logger, channel: relation_list_menu }

    ngmore.menu.main_menu:
        class: Knp\Menu\MenuItem
        public: false
        factory: ["@ngmore.menu.relation_list_menu_builder", createRelationListMenu]
        arguments:
            - main_menu
        tags:
            - { name: knp_menu.menu, alias: ngmore_main_menu }

    ngmore.menu.additional_menu:
        class: Knp\Menu\MenuItem
        public: false
        factory: ["@ngmore.menu.relation_list_menu_builder", createRelationListMenu]
        arguments:
            - additional_menu
        tags:
            - { name: knp_menu.menu, alias: ngmore_additional_menu }
