services:
    ngmore.menu.relation_list_menu_builder:
        class: Netgen\Bundle\MoreBundle\Menu\RelationListMenuBuilder
        public: false
        arguments:
            - "@ngmore.menu.factory.location"
            - "@netgen.ezplatform_site.load_service"
            - "@ngmore.helper.site_info_helper"
            - "@?logger"
        tags:
            - { name: monolog.logger, channel: ngmore }

    ngmore.menu.factory.location:
        class: Netgen\Bundle\MoreBundle\Menu\Factory\LocationFactory
        public: false
        arguments:
            - "@ngmore.menu.factory.location.extension.fallback"
            - []

    ngmore.menu.factory.location.extension.fallback:
        class: Netgen\Bundle\MoreBundle\Menu\Factory\LocationFactory\FallbackExtension
        public: false
        arguments:
            - "@router"

    ngmore.menu.factory.location.extension.shortcut:
        class: Netgen\Bundle\MoreBundle\Menu\Factory\LocationFactory\ShortcutExtension
        public: false
        arguments:
            - "@netgen.ezplatform_site.load_service"
            - "@router"
            - "@?logger"
        tags:
            - { name: ngmore.menu.factory.location.extension, priority: 0 }
            - { name: monolog.logger, channel: ngmore }

    ngmore.menu.factory.location.extension.menu_item:
        class: Netgen\Bundle\MoreBundle\Menu\Factory\LocationFactory\MenuItemExtension
        public: false
        arguments:
            - "@netgen.ezplatform_site.load_service"
            - "@netgen.ezplatform_site.filter_service"
            - "@router"
            - "@?logger"
        tags:
            - { name: ngmore.menu.factory.location.extension, priority: 0 }
            - { name: monolog.logger, channel: ngmore }

    ngmore.menu.main_menu:
        class: Knp\Menu\MenuItem
        public: false
        factory: ["@ngmore.menu.relation_list_menu_builder", createRelationListMenu]
        arguments:
            - main_menu
        tags:
            - { name: knp_menu.menu, alias: ngmore_main_menu }

    ngmore.menu.additional_menu:
        class: Knp\Menu\MenuItem
        public: false
        factory: ["@ngmore.menu.relation_list_menu_builder", createRelationListMenu]
        arguments:
            - additional_menu
        tags:
            - { name: knp_menu.menu, alias: ngmore_additional_menu }
