parameters:
    ngmore.pagerfanta.view.ngmore_bootstrap3.class: Netgen\Bundle\MoreBundle\Pagerfanta\View\NetgenMoreBootstrap3View

services:
    ngmore.pagerfanta.view.ngmore_bootstrap3:
        class: %ngmore.pagerfanta.view.ngmore_bootstrap3.class%
        parent: pagerfanta.view.twitter_bootstrap3
        tags:
            - {name: pagerfanta.view, alias: ngmore_bootstrap3}
