parameters:
    ngmore.pagerfanta.view.ngmore.class: Netgen\Bundle\MoreBundle\Pagerfanta\View\NetgenMoreView

services:
    ngmore.pagerfanta.view.ngmore:
        class: "%ngmore.pagerfanta.view.ngmore.class%"
        arguments:
            - "@twig"
        calls:
            - [setDefaultTemplate, [$template.pagerfanta.ngmore;ngmore$]]
        tags:
            - {name: pagerfanta.view, alias: ngmore}
