services:
    ngmore.pagerfanta.view.ngmore:
        class: Netgen\Bundle\MoreBundle\Pagerfanta\View\NetgenMoreView
        public: true
        arguments:
            - "@twig"
        calls:
            - [setDefaultTemplate, [$template.pagerfanta.ngmore;ngmore$]]
        tags:
            - {name: pagerfanta.view, alias: ngmore}
