parameters:
    ngmore.pagerfanta.view.ngmore_bootstrap3.class: Netgen\Bundle\MoreBundle\Pagerfanta\View\NetgenMoreBootstrap3View
    ngmore.pagerfanta.view.ngmore.class: Netgen\Bundle\MoreBundle\Pagerfanta\View\NetgenMoreView

services:
    ngmore.pagerfanta.view.ngmore_bootstrap3:
        class: "%ngmore.pagerfanta.view.ngmore_bootstrap3.class%"
        parent: pagerfanta.view.twitter_bootstrap3
        tags:
            - {name: pagerfanta.view, alias: ngmore_bootstrap3}

    ngmore.pagerfanta.view.ngmore:
        class: "%ngmore.pagerfanta.view.ngmore.class%"
        arguments:
            - "@twig"
        calls:
            - [setDefaultTemplate, [$template.pagerfanta.ngmore;ngmore$]]
        tags:
            - {name: pagerfanta.view, alias: ngmore}
