parameters:
    ngmore.default.locale.conversion_map: %ezpublish.locale.conversion_map%
    ngmore.legacy_mapper.configuration.options:
        enabled_legacy_settings: []

    ngmore.default.pagelayout: NetgenMoreBundle::pagelayout_empty.html.twig

    ngmore.default.site_domain: localhost

    ngmore.default.locations.sidebars_parent.id: ~

    ngmore.default.site_settings.google_tag_manager_code: ~
    ngmore.default.site_settings.jwplayer_id: 'gYe8hbFO'
    ngmore.default.site_settings.jwplayer_key: ~
    ngmore.default.site_settings.meta_data: []
    ngmore.default.site_settings.show_path_in_title: false
    ngmore.default.site_settings.site_name: 'NG More'

    ngmore.default.path_helper.excluded_content_types: ['ng_container', 'folder']

    ngmore.default.user.content_type_identifier: 'user'
    ngmore.default.user.user_group_content_id: 11
    ngmore.default.user.auto_enable: false
    ngmore.default.user.activate_hash_validity_time: 3600
    ngmore.default.user.forgot_password_hash_validity_time: 3600

    ngmore.default.mail.sender_email: 'info@example.com'
    ngmore.default.mail.sender_name: 'Netgen More'

    ngmore.default.content_view.show_invisible_locations: false
    # Controls handling Legacy Stack fallback error responses through Symfony exceptions (401, 403, 404...)
    ngmore.default.content_view.handle_legacy_fallback_error_result: true

    netgen.ezforms.form.type.fieldtype.ezuser.parameters.min_password_length: 0

    ngmore.default.template.errors.default: 'NetgenMoreBundle::errors/default.html.twig'

    ngmore.default.template.pagerfanta.ngmore: 'NetgenMoreBundle:pagerfanta:ngmore.html.twig'
