parameters:
    ngmore.default.locale.conversion_map: %ezpublish.locale.conversion_map%
    ngmore.legacy_mapper.configuration.options:
        enabled_legacy_settings: []
    ngmore.default.site_settings.google_tag_manager_code: ~
    ngmore.default.site_settings.jwplayer_key: ~
    ngmore.default.path_helper.excluded_content_types: ['ng_container', 'folder']
    ngmore.default.user_register.user_group_content_id: 11
    ngmore.default.user_register.auto_enable: false
