parameters:
    ngmore.default.locale.conversion_map: %ezpublish.locale.conversion_map%

    ngmore.default.pagelayout: NetgenMoreBundle::pagelayout_empty.html.twig

    ngmore.default.site_domain: localhost

    ngmore.default.locations.site_info.id: ~
    ngmore.default.locations.sidebars_parent.id: ~

    ngmore.default.google_maps.latitude: 45.79849
    ngmore.default.google_maps.longitude: 15.90777
    ngmore.default.google_maps.zoom: 13
    # Valid options for map type are ROADMAP, SATELLITE, HYBRID, TERRAIN
    ngmore.default.google_maps.map_type: ROADMAP

    ngmore.default.site_settings.google_analytics_code: ~
    ngmore.default.site_settings.google_analytics_universal: true
    ngmore.default.site_settings.google_tag_manager_code: ~
    ngmore.default.site_settings.add_this_code: ~
    ngmore.default.site_settings.typekit_code: ~
    ngmore.default.site_settings.sublime_video_code: ~
    ngmore.default.site_settings.facebook_api: false
    ngmore.default.site_settings.facebook_locale: en_US
