parameters:
    ngmore.default.locale.conversion_map: %ezpublish.locale.conversion_map%
    ngmore.legacy_mapper.configuration.options:
        enabled_legacy_settings: []

    ngmore.default.site_settings.google_tag_manager_code: ~
