parameters:
    ngmore.default.locale.conversion_map: "%ezpublish.locale.conversion_map%"

    ngmore.default.pagelayout: '@@NetgenMore/pagelayout_empty.html.twig'

    ngmore.default.site_domain: localhost

    ngmore.default.locations.site_info.id: ~

    ngmore.default.google_maps.latitude: 45.79849
    ngmore.default.google_maps.longitude: 15.90777
    ngmore.default.google_maps.zoom: 13
    # Valid options for map type are ROADMAP, SATELLITE, HYBRID, TERRAIN
    ngmore.default.google_maps.map_type: ROADMAP

    ngmore.default.site_settings.google_analytics_code: ~
    ngmore.default.site_settings.google_analytics_universal: true
    ngmore.default.site_settings.google_tag_manager_code: ~
    ngmore.default.site_settings.add_this_code: ~
    ngmore.default.site_settings.typekit_code: ~
    ngmore.default.site_settings.facebook_api: false
    ngmore.default.site_settings.facebook_locale: en_US
    ngmore.default.site_settings.jwplayer_id: 'gYe8hbFO'
    ngmore.default.site_settings.jwplayer_key: ~
    ngmore.default.site_settings.meta_data: []
    ngmore.default.site_settings.show_path_in_title: false

    ngmore.default.path_helper.excluded_content_types: ['ng_container', 'folder']

    ngmore.default.mail.sender_email: 'info@example.com'
    ngmore.default.mail.sender_name: 'Netgen More'
    ngmore.default.mail.admin_email: ~
    ngmore.default.mail.admin_name: ~

    ngmore.default.user.content_type_identifier: 'user'
    ngmore.default.user.user_group_content_id: 11
    ngmore.default.user.auto_enable: false
    ngmore.default.user.require_admin_activation: false
    ngmore.default.user.activate_hash_validity_time: 3600
    ngmore.default.user.forgot_password_hash_validity_time: 3600
    ngmore.default.user.mail.admin_email: "%ngmore.default.mail.admin_email%"
    ngmore.default.user.mail.admin_name: "%ngmore.default.mail.admin_name%"

    ngmore.default.view.shared_max_age: 86400

    ngmore.default.search.default_limit: 10
    ngmore.default.search.content_types: []

    ngmore.default.template.errors.default: '@@NetgenMore/errors/default.html.twig'
    ngmore.default.template.pagerfanta.ngmore: '@@NetgenMore/pagerfanta/ngmore.html.twig'
    ngmore.default.template.search: '@@NetgenMore/search/search.html.twig'
    ngmore.default.template.menu: '@@KnpMenu/menu.html.twig'

    # Non siteaccess aware params
    ngmore.ezfile_storage_path: '/var/site/storage/original'

    netgen.ezforms.form.type.fieldtype.ezuser.parameters.min_password_length: 0
