ngmore_download:
    path: /download/{contentId}/{fieldId}
    defaults:
        _controller: ngmore.controller.download:downloadFile
    methods: [GET]

ngmore_sitemap:
    path: /sitemap
    defaults:
        _controller: ngmore.controller.sitemap:viewSitemap
    methods: [GET]

ngmore_user_register:
    path:   /register
    defaults:   { _controller: ngmore.controller.user:register }