parameters:
    ezpublish.controller.page.view.class: Netgen\Bundle\MoreBundle\Controller\PageController

    ezpublish.persistence.legacy.search.gateway.criterion_handler.common.field.class: Netgen\Bundle\MoreBundle\Core\Persistence\Legacy\Content\Search\Common\Gateway\CriterionHandler\Field
    ezpublish.persistence.legacy.search.gateway.criterion_field_value_handler.composite.class: Netgen\Bundle\MoreBundle\Core\Persistence\Legacy\Content\Search\Common\Gateway\CriterionHandler\FieldValue\Handler\Composite
    ezpublish.persistence.legacy.search.gateway.sort_clause_handler.common.field_length.class: Netgen\Bundle\MoreBundle\Core\Persistence\Legacy\Content\Search\Common\Gateway\SortClauseHandler\FieldLength

    netgen_more.controller.page_layout.class: Netgen\Bundle\MoreBundle\Controller\PageLayoutController

    netgen_more.helper.path_helper.class: Netgen\Bundle\MoreBundle\Helper\PathHelper
    netgen_more.helper.layout_helper.class: Netgen\Bundle\MoreBundle\Helper\LayoutHelper

    netgen_more.templating.global_helper.class: Netgen\Bundle\MoreBundle\Templating\GlobalHelper
    netgen_more.templating.twig.extension.class: Netgen\Bundle\MoreBundle\Templating\Twig\Extension\NetgenMoreExtension

    netgen_more.data_collector.legacy_debug_data_collector.class: Netgen\Bundle\MoreBundle\DataCollector\LegacyDebugDataCollector

services:
    ezpublish.persistence.legacy.search.gateway.sort_clause_handler.common.field_length:
        class: %ezpublish.persistence.legacy.search.gateway.sort_clause_handler.common.field_length.class%
        parent: ezpublish.persistence.legacy.search.gateway.sort_clause_handler.common.field
        tags:
            - {name: ezpublish.persistence.legacy.search.gateway.sort_clause_handler.content}
            - {name: ezpublish.persistence.legacy.search.gateway.sort_clause_handler.location}

    netgen_more.controller.page_layout:
        class: %netgen_more.controller.page_layout.class%
        parent: ezpublish.controller.base

    netgen_more.helper.path_helper:
        class: %netgen_more.helper.path_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.config.resolver
            - @ezpublish.translation_helper
            - @router

    netgen_more.helper.layout_helper:
        class: %netgen_more.helper.layout_helper.class%
        arguments:
            - @ezpublish.api.repository
            - @netgen_more.helper.path_helper
            - @ezpublish.config.resolver

    netgen_more.templating.global_helper:
        class: %netgen_more.templating.global_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @netgen_more.helper.layout_helper
            - @ezpublish.config.resolver
        calls:
            - [setRequest, [@?request=]]

    netgen_more.templating.twig.extension:
        class: %netgen_more.templating.twig.extension.class%
        arguments:
            - @netgen_more.helper.path_helper
            - @netgen_more.templating.global_helper
        tags:
            - { name: twig.extension }

    netgen_more.data_collector.legacy_debug_data_collector:
        class: %netgen_more.data_collector.legacy_debug_data_collector.class%
        arguments:
            - @ezpublish_legacy.kernel
        tags:
            - { name: data_collector, template: "NetgenMoreBundle:Profiler:LegacyDebug.html.twig", id: "ngmore_legacy_debug" }
