parameters:
    ngmore.search.legacy.gateway.sort_clause_handler.common.field_length.class: Netgen\Bundle\MoreBundle\Core\Search\Legacy\Content\Common\Gateway\SortClauseHandler\FieldLength

    ngmore.controller.full_view.class: Netgen\Bundle\MoreBundle\Controller\FullViewController
    ngmore.controller.embed_view.class: Netgen\Bundle\MoreBundle\Controller\EmbedViewController
    ngmore.controller.block_view.class: Netgen\Bundle\MoreBundle\Controller\BlockViewController
    ngmore.controller.page_layout.class: Netgen\Bundle\MoreBundle\Controller\PageLayoutController
    ngmore.controller.parts.class: Netgen\Bundle\MoreBundle\Controller\PartsController
    ngmore.controller.sitemap.class: Netgen\Bundle\MoreBundle\Controller\SitemapController
    ngmore.controller.user.class: Netgen\Bundle\MoreBundle\Controller\UserController

    ngmore.helper.path_helper.class: Netgen\Bundle\MoreBundle\Helper\PathHelper
    ngmore.helper.site_info_helper.class: Netgen\Bundle\MoreBundle\Helper\SiteInfoHelper
    ngmore.helper.sort_clause_helper.class: Netgen\Bundle\MoreBundle\Helper\SortClauseHelper
    ngmore.helper.layout_helper.class: Netgen\Bundle\MoreBundle\Helper\LayoutHelper
    ngmore.helper.mail_helper.class: Netgen\Bundle\MoreBundle\Helper\MailHelper

    ngmore.entity.nguser_setting.class: Netgen\Bundle\MoreBundle\Entity\NgUserSetting
    ngmore.entity.ezuser_accountkey.class: Netgen\Bundle\MoreBundle\Entity\EzUserAccountKey

    ngmore.slot.create_user.class: Netgen\Bundle\MoreBundle\Core\Slot\CreateUserSlot

    ngmore.matcher.config_resolver.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ConfigResolverBased
    ngmore.matcher.content.content_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\Content
    ngmore.matcher.content.content_type_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\ContentType
    ngmore.matcher.content.content_type_group_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\ContentTypeGroup
    ngmore.matcher.content.location_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\Location
    ngmore.matcher.content.parent_content_type_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\ParentContentType
    ngmore.matcher.content.parent_location_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\ParentLocation
    ngmore.matcher.content.remote_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\Remote
    ngmore.matcher.content.section_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\ContentBased\Id\Section
    ngmore.matcher.block.block_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\Block\Id\Block
    ngmore.matcher.block.zone_id.class: Netgen\Bundle\MoreBundle\Core\MVC\Symfony\Matcher\Block\Id\Zone

    ngmore.context_provider.session.class: Netgen\Bundle\MoreBundle\ContextProvider\SessionContextProvider
    ngmore.context_provider.user.class: Netgen\Bundle\MoreBundle\ContextProvider\UserContextProvider

services:
    ngmore.search.legacy.gateway.sort_clause_handler.common.field_length:
        class: %ngmore.search.legacy.gateway.sort_clause_handler.common.field_length.class%
        parent: ezpublish.search.legacy.gateway.sort_clause_handler.common.field
        tags:
            - {name: ezpublish.search.legacy.gateway.sort_clause_handler.content}
            - {name: ezpublish.search.legacy.gateway.sort_clause_handler.location}

    ngmore.controller.full_view:
        class: %ngmore.controller.full_view.class%
        parent: ezpublish.controller.base

    ngmore.controller.embed_view:
        class: %ngmore.controller.embed_view.class%
        parent: ezpublish.controller.base
        arguments:
            - @?logger

    ngmore.controller.block_view:
        class: %ngmore.controller.block_view.class%
        parent: ezpublish.controller.base

    ngmore.controller.page_layout:
        class: %ngmore.controller.page_layout.class%
        parent: ezpublish.controller.base

    ngmore.controller.parts:
        class: %ngmore.controller.parts.class%
        parent: ezpublish.controller.base

    ngmore.controller.sitemap:
        class: %ngmore.controller.sitemap.class%
        parent: ezpublish.controller.base

    ngmore.controller.user:
        class: %ngmore.controller.user.class%
        parent: ezpublish.controller.base
        arguments:
            - @ezpublish.api.service.user
            - @event_dispatcher

    ngmore.helper.path_helper:
        class: %ngmore.helper.path_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.config.resolver
            - @ezpublish.translation_helper
            - @router
            - @ezpublish.api.service.content_type

    ngmore.helper.site_info_helper:
        class: %ngmore.helper.site_info_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.api.service.content
            - @ezpublish.config.resolver

    ngmore.helper.sort_clause_helper:
        class: %ngmore.helper.sort_clause_helper.class%

    ngmore.helper.layout_helper:
        class: %ngmore.helper.layout_helper.class%
        arguments:
            - @ezpublish.api.repository
            - @ezpublish.spi.search.legacy
            - @ngmore.helper.path_helper
            - @ezpublish.translation_helper
            - @ezpublish.config.resolver

    ngmore.helper.mail_helper:
        class: %ngmore.helper.mail_helper.class%
        arguments:
            - @mailer
            - @templating
            - @router
            - @translator
            - @ezpublish.config.resolver

    ngmore.repository.nguser_setting:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - %ngmore.entity.nguser_setting.class%

    ngmore.repository.ezuser_accountkey:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - %ngmore.entity.ezuser_accountkey.class%

    ngmore.slot.create_user:
        class: %ngmore.slot.create_user.class%
        arguments:
            - @ezpublish.api.service.user
            - @ngmore.repository.nguser_setting
        tags:
            - { name: ezpublish.api.slot, signal: UserService\CreateUserSignal }

    ngmore.matcher.config_resolver:
        class: %ngmore.matcher.config_resolver.class%
        abstract: true
        arguments: [@ezpublish.config.resolver]

    ngmore.matcher.content.content_id:
        class: %ngmore.matcher.content.content_id.class%
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.content.content_type_id:
        class: %ngmore.matcher.content.content_type_id.class%
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.content.content_type_group_id:
        class: %ngmore.matcher.content.content_type_group_id.class%
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.content.location_id:
        class: %ngmore.matcher.content.location_id.class%
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.content.parent_content_type_id:
        class: %ngmore.matcher.content.parent_content_type_id.class%
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.content.parent_location_id:
        class: %ngmore.matcher.content.parent_location_id.class%
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.content.remote_id:
        class: %ngmore.matcher.content.remote_id.class%
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.content.section_id:
        class: %ngmore.matcher.content.section_id.class%
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.block.block_id:
        class: %ngmore.matcher.block.block_id.class%
        parent: ngmore.matcher.config_resolver

    ngmore.matcher.block.zone_id:
        class: %ngmore.matcher.block.zone_id.class%
        parent: ngmore.matcher.config_resolver

#    Custom user context hash providers are disabled by default.
#    Enable them in your project if needed by copying one of the
#    following service definitions.
#
#    ngmore.context_provider.session:
#        class: %ngmore.context_provider.session.class%
#        arguments:
#            - @session
#    tags:
#        - { name: fos_http_cache.user_context_provider }
#
#    ngmore.context_provider.user:
#        class: %ngmore.context_provider.user.class%
#        arguments:
#            - @ezpublish.api.repository
#    tags:
#        - { name: fos_http_cache.user_context_provider }
