parameters:
    ezpublish.controller.page.view.class: Netgen\Bundle\MoreBundle\Controller\PageController

    netgen_more.controller.page_layout.class: Netgen\Bundle\MoreBundle\Controller\PageLayoutController

    netgen_more.templating.global_helper.class: Netgen\Bundle\MoreBundle\Templating\GlobalHelper

    netgen_more.helper.path_helper.class: Netgen\Bundle\MoreBundle\Helper\PathHelper

    netgen_more.templating.twig.extension.class: Netgen\Bundle\MoreBundle\Templating\Twig\Extension\NetgenMoreExtension

    netgen_more.data_collector.legacy_debug_data_collector.class: Netgen\Bundle\MoreBundle\DataCollector\LegacyDebugDataCollector

services:
    netgen_more.controller.page_layout:
        class: %netgen_more.controller.page_layout.class%
        parent: ezpublish.controller.base

    netgen_more.templating.global_helper:
        class: %netgen_more.templating.global_helper.class%
        parent: ezpublish.templating.global_helper.legacy
        calls:
          - [setLegacyKernel, [@ezpublish_legacy.kernel]]
          - [setContentService, [@ezpublish.api.service.content]]

    ezpublish.templating.global_helper:
        alias: netgen_more.templating.global_helper

    netgen_more.helper.path_helper:
        class: %netgen_more.helper.path_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.config.resolver
            - @ezpublish.translation_helper
            - @router

    netgen_more.templating.twig.extension:
        class: %netgen_more.templating.twig.extension.class%
        arguments: [@netgen_more.helper.path_helper]
        tags:
            - { name: twig.extension }

    netgen_more.data_collector.legacy_debug_data_collector:
        class: %netgen_more.data_collector.legacy_debug_data_collector.class%
        arguments:
            - @ezpublish_legacy.kernel
        tags:
            - { name: data_collector, template: "NetgenMoreBundle:Profiler:LegacyDebug.html.twig", id: "ngmore_legacy_debug" }
