services:
    ngmore.controller.full_view:
        class: Netgen\Bundle\MoreBundle\Controller\FullViewController
        public: true
        parent: netgen.ezplatform_site.controller.base
        arguments:
            - "@router"

    ngmore.controller.embed_view:
        class: Netgen\Bundle\MoreBundle\Controller\EmbedViewController
        public: true
        parent: netgen.ezplatform_site.controller.base
        arguments:
            - "@router"
            - "@?logger"

    ngmore.controller.search:
        class: Netgen\Bundle\MoreBundle\Controller\SearchController
        public: true
        parent: netgen.ezplatform_site.controller.base

    ngmore.controller.page_layout:
        class: Netgen\Bundle\MoreBundle\Controller\PageLayoutController
        public: true
        parent: netgen.ezplatform_site.controller.base
        arguments:
            - "@knp_menu.menu_provider"
            - "@knp_menu.renderer_provider"
            - "@ezplatform.http_cache.tag_handler"

    ngmore.controller.parts:
        class: Netgen\Bundle\MoreBundle\Controller\PartsController
        public: true
        parent: netgen.ezplatform_site.controller.base

    ngmore.controller.download:
        class: Netgen\Bundle\MoreBundle\Controller\DownloadController
        public: true
        parent: netgen.ezplatform_site.controller.base
        arguments:
            - "@ezpublish.fieldType.ezbinaryfile.io_service"
            - "@ezpublish.fieldType.ezimage.io_service"
            - "@translator"
            - "@event_dispatcher"

    ngmore.controller.user:
        class: Netgen\Bundle\MoreBundle\Controller\UserController
        public: true
        parent: netgen.ezplatform_site.controller.base
        arguments:
            - "@ezpublish.api.service.user"
            - "@event_dispatcher"
            - "@form.factory"
            - "@ngmore.repository.ezuser_accountkey"

    ngmore.helper.path_helper:
        class: Netgen\Bundle\MoreBundle\Helper\PathHelper
        public: false
        arguments:
            - "@netgen.ezplatform_site.load_service"
            - "@ezpublish.config.resolver"
            - "@router"

    ngmore.helper.site_info_helper:
        class: Netgen\Bundle\MoreBundle\Helper\SiteInfoHelper
        public: false
        arguments:
            - "@netgen.ezplatform_site.load_service"
            - "@ezpublish.config.resolver"

    ngmore.helper.mail_helper:
        class: Netgen\Bundle\MoreBundle\Helper\MailHelper
        public: false
        arguments:
            - "@mailer"
            - "@templating"
            - "@router"
            - "@translator"
            - "@ezpublish.config.resolver"
            - "@?logger"

    ngmore.repository.nguser_setting:
        class: Doctrine\ORM\EntityRepository
        public: false
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - Netgen\Bundle\MoreBundle\Entity\NgUserSetting

    ngmore.repository.ezuser_accountkey:
        class: Doctrine\ORM\EntityRepository
        public: false
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - Netgen\Bundle\MoreBundle\Entity\EzUserAccountKey

    ngmore.slot.create_user:
        class: Netgen\Bundle\MoreBundle\Core\Slot\CreateUserSlot
        public: false
        arguments:
            - "@ezpublish.api.service.user"
            - "@ngmore.repository.nguser_setting"
        tags:
            - { name: ezpublish.api.slot, signal: UserService\CreateUserSignal }

    ngmore.routing.site_content_url_alias_router:
        class: Netgen\Bundle\MoreBundle\Routing\SiteContentUrlAliasRouter
        public: false
        arguments:
            - "@ezpublish.urlalias_generator"
            - "@?router.request_context"
        tags:
            - { name: router, priority: 200 }

    ngmore.routing.site_location_url_alias_router:
        class: Netgen\Bundle\MoreBundle\Routing\SiteLocationUrlAliasRouter
        public: false
        arguments:
            - "@ezpublish.urlalias_generator"
            - "@?router.request_context"
        tags:
            - { name: router, priority: 200 }

#    Custom user context hash providers are disabled by default.
#    Enable them in your project if needed by copying one of the
#    following service definitions.
#
#    ngmore.context_provider.session:
#        class: Netgen\Bundle\MoreBundle\ContextProvider\SessionContextProvider
#        public: false
#        arguments:
#            - "@session"
#    tags:
#        - { name: fos_http_cache.user_context_provider }
#
#    ngmore.context_provider.user:
#        class: Netgen\Bundle\MoreBundle\ContextProvider\UserContextProvider
#        public: false
#        arguments:
#            - "@ezpublish.api.repository"
#    tags:
#        - { name: fos_http_cache.user_context_provider }
