parameters:
    ngmore.controller.full_view.class: Netgen\Bundle\MoreBundle\Controller\FullViewController
    ngmore.controller.embed_view.class: Netgen\Bundle\MoreBundle\Controller\EmbedViewController
    ngmore.controller.block_view.class: Netgen\Bundle\MoreBundle\Controller\BlockViewController
    ngmore.controller.page_layout.class: Netgen\Bundle\MoreBundle\Controller\PageLayoutController
    ngmore.controller.parts.class: Netgen\Bundle\MoreBundle\Controller\PartsController
    ngmore.controller.download.class: Netgen\Bundle\MoreBundle\Controller\DownloadController
    ngmore.controller.sitemap.class: Netgen\Bundle\MoreBundle\Controller\SitemapController
    ngmore.controller.user.class: Netgen\Bundle\MoreBundle\Controller\UserController

    ngmore.helper.path_helper.class: Netgen\Bundle\MoreBundle\Helper\PathHelper
    ngmore.helper.site_info_helper.class: Netgen\Bundle\MoreBundle\Helper\SiteInfoHelper
    ngmore.helper.sort_clause_helper.class: Netgen\Bundle\MoreBundle\Helper\SortClauseHelper
    ngmore.helper.layout_helper.class: Netgen\Bundle\MoreBundle\Helper\LayoutHelper
    ngmore.helper.mail_helper.class: Netgen\Bundle\MoreBundle\Helper\MailHelper

    ngmore.data_collector.legacy_debug_data_collector.class: Netgen\Bundle\MoreBundle\DataCollector\LegacyDebugDataCollector

    ngmore.legacy_mapper.configuration.class: Netgen\Bundle\MoreBundle\LegacyMapper\Configuration

    ngmore.entity.nguser_setting.class: Netgen\Bundle\MoreBundle\Entity\NgUserSetting

    ngmore.slot.create_user.class: Netgen\Bundle\MoreBundle\Core\Slot\CreateUserSlot

services:
    ngmore.controller.full_view:
        class: %ngmore.controller.full_view.class%
        parent: ezpublish.controller.base

    ngmore.controller.embed_view:
        class: %ngmore.controller.embed_view.class%
        parent: ezpublish.controller.base
        arguments:
            - @?logger

    ngmore.controller.block_view:
        class: %ngmore.controller.block_view.class%
        parent: ezpublish.controller.base

    ngmore.controller.page_layout:
        class: %ngmore.controller.page_layout.class%
        parent: ezpublish.controller.base

    ngmore.controller.parts:
        class: %ngmore.controller.parts.class%
        parent: ezpublish.controller.base

    ngmore.controller.download:
        class: %ngmore.controller.download.class%
        parent: ezpublish.controller.base

    ngmore.controller.sitemap:
        class: %ngmore.controller.sitemap.class%
        parent: ezpublish.controller.base

    ngmore.controller.user:
        class: %ngmore.controller.user.class%
        parent: ezpublish.controller.base
        arguments:
            - @ezpublish.api.service.user
            - @ngmore.helper.mail_helper

    ngmore.helper.path_helper:
        class: %ngmore.helper.path_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.config.resolver
            - @ezpublish.translation_helper
            - @router
            - @ezpublish.api.service.content_type

    ngmore.helper.site_info_helper:
        class: %ngmore.helper.site_info_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.api.service.content
            - @ezpublish.config.resolver

    ngmore.helper.sort_clause_helper:
        class: %ngmore.helper.sort_clause_helper.class%

    ngmore.helper.layout_helper:
        class: %ngmore.helper.layout_helper.class%
        arguments:
            - @ezpublish.api.repository
            - @ngmore.helper.path_helper
            - @ezpublish.translation_helper
            - @ezpublish.config.resolver

    ngmore.helper.mail_helper:
        class: %ngmore.helper.mail_helper.class%
        arguments:
            - @mailer
            - @templating
            - @router
            - @translator
            - @ezpublish.config.resolver

    ngmore.data_collector.legacy_debug_data_collector:
        class: %ngmore.data_collector.legacy_debug_data_collector.class%
        arguments:
            - @ezpublish_legacy.kernel
            - @fos_http_cache.user_context.request_matcher
        tags:
            - { name: data_collector, template: 'NetgenMoreBundle:Profiler:LegacyDebug.html.twig', id: 'ngmore_legacy_debug' }

    ngmore.legacy_mapper.configuration:
        class: %ngmore.legacy_mapper.configuration.class%
        arguments:
            - @ezpublish.config.resolver.core
            - %ngmore.legacy_mapper.configuration.options%
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: kernel.event_subscriber }

    ngmore.repository.nguser_setting:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - %ngmore.entity.nguser_setting.class%

    ngmore.slot.create_user:
        class: %ngmore.slot.create_user.class%
        arguments:
            - @ezpublish.api.service.user
            - @ngmore.repository.nguser_setting
        tags:
            - { name: ezpublish.api.slot, signal: UserService\CreateUserSignal }
