parameters:
    ezpublish.controller.page.view.class: Netgen\Bundle\MoreBundle\Controller\PageController
    ezpublish.controller.content.view.class: Netgen\Bundle\MoreBundle\Controller\ViewController

    netgen_more.controller.page_layout.class: Netgen\Bundle\MoreBundle\Controller\PageLayoutController
    netgen_more.component.page_layout.class: Netgen\Bundle\MoreBundle\Component\PageLayout

    netgen_more.response_manager.class: Netgen\Bundle\MoreBundle\LegacyResponse\LegacyResponseManager

    netgen_more.templating.global_helper.class: Netgen\Bundle\MoreBundle\Templating\GlobalHelper

    netgen_more.helper.path_helper.class: Netgen\Bundle\MoreBundle\Helper\PathHelper

    netgen_more.templating.twig.extension.class: Netgen\Bundle\MoreBundle\Templating\Twig\Extension\NetgenMoreExtension

services:
    netgen_more.controller.page_layout:
        class: %netgen_more.controller.page_layout.class%
        parent: ezpublish.controller.base

    netgen_more.component.page_layout:
        class: %netgen_more.component.page_layout.class%
        arguments:
            - @ezpublish_legacy.kernel
            - @ezpublish.api.repository
            - @ezpublish.config.resolver

    # START: Temporary workaround because original 'ezpublish_legacy.response_manager' service has private variables
    netgen_more.response_manager:
        class: %netgen_more.response_manager.class%
        arguments: [@templating, @ezpublish.config.resolver]
        calls:
            - [setContainer, [@service_container]]

    ezpublish_legacy.response_manager:
        alias: netgen_more.response_manager
    # END: Temporary workaround because original 'ezpublish_legacy.response_manager' service has private variables

    netgen_more.templating.global_helper:
        class: %netgen_more.templating.global_helper.class%
        parent: ezpublish.templating.global_helper.legacy
        calls:
          - [setLegacyKernel, [@ezpublish_legacy.kernel]]
          - [setContentService, [@ezpublish.api.service.content]]

    ezpublish.templating.global_helper:
        alias: netgen_more.templating.global_helper

    netgen_more.helper.path_helper:
        class: %netgen_more.helper.path_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.config.resolver
            - @ezpublish.translation_helper
            - @router

    netgen_more.templating.twig.extension:
        class: %netgen_more.templating.twig.extension.class%
        arguments: [@netgen_more.helper.path_helper]
        tags:
            - { name: twig.extension }
