parameters:
    ngmore.persistence.legacy.search.gateway.sort_clause_handler.common.field_length.class: Netgen\Bundle\MoreBundle\Core\Persistence\Legacy\Content\Search\Common\Gateway\SortClauseHandler\FieldLength

    ngmore.controller.full_view.class: Netgen\Bundle\MoreBundle\Controller\FullViewController
    ngmore.controller.embed_view.class: Netgen\Bundle\MoreBundle\Controller\EmbedViewController
    ngmore.controller.block_view.class: Netgen\Bundle\MoreBundle\Controller\BlockViewController
    ngmore.controller.page_layout.class: Netgen\Bundle\MoreBundle\Controller\PageLayoutController
    ngmore.controller.parts.class: Netgen\Bundle\MoreBundle\Controller\PartsController

    ngmore.helper.path_helper.class: Netgen\Bundle\MoreBundle\Helper\PathHelper
    ngmore.helper.site_info_helper.class: Netgen\Bundle\MoreBundle\Helper\SiteInfoHelper
    ngmore.helper.sort_clause_helper.class: Netgen\Bundle\MoreBundle\Helper\SortClauseHelper
    ngmore.helper.layout_helper.class: Netgen\Bundle\MoreBundle\Helper\LayoutHelper

    ngmore.data_collector.legacy_debug_data_collector.class: Netgen\Bundle\MoreBundle\DataCollector\LegacyDebugDataCollector

    ngmore.limitation_type.function_list.class: Netgen\Bundle\MoreBundle\Core\Limitation\FunctionListLimitationType

    ngmore.legacy_mapper.configuration.class: Netgen\Bundle\MoreBundle\LegacyMapper\Configuration

services:
    ngmore.persistence.legacy.search.gateway.sort_clause_handler.common.field_length:
        class: %ngmore.persistence.legacy.search.gateway.sort_clause_handler.common.field_length.class%
        parent: ezpublish.persistence.legacy.search.gateway.sort_clause_handler.common.field
        tags:
            - {name: ezpublish.persistence.legacy.search.gateway.sort_clause_handler.content}
            - {name: ezpublish.persistence.legacy.search.gateway.sort_clause_handler.location}

    ngmore.controller.full_view:
        class: %ngmore.controller.full_view.class%
        parent: ezpublish.controller.base

    ngmore.controller.embed_view:
        class: %ngmore.controller.embed_view.class%
        parent: ezpublish.controller.base
        arguments:
            - @?logger

    ngmore.controller.block_view:
        class: %ngmore.controller.block_view.class%
        parent: ezpublish.controller.base

    ngmore.controller.page_layout:
        class: %ngmore.controller.page_layout.class%
        parent: ezpublish.controller.base

    ngmore.controller.parts:
        class: %ngmore.controller.parts.class%
        parent: ezpublish.controller.base

    ngmore.helper.path_helper:
        class: %ngmore.helper.path_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.config.resolver
            - @ezpublish.translation_helper
            - @router

    ngmore.helper.site_info_helper:
        class: %ngmore.helper.site_info_helper.class%
        arguments:
            - @ezpublish.api.service.location
            - @ezpublish.api.service.content
            - @ezpublish.config.resolver

    ngmore.helper.sort_clause_helper:
        class: %ngmore.helper.sort_clause_helper.class%

    ngmore.helper.layout_helper:
        class: %ngmore.helper.layout_helper.class%
        arguments:
            - @ezpublish.api.repository
            - @ngmore.helper.path_helper
            - @ezpublish.translation_helper
            - @ezpublish.config.resolver

    ngmore.data_collector.legacy_debug_data_collector:
        class: %ngmore.data_collector.legacy_debug_data_collector.class%
        arguments:
            - @ezpublish_legacy.kernel
            - @?fos_http_cache.user_context.request_matcher
        tags:
            - { name: data_collector, template: 'NetgenMoreBundle:Profiler:LegacyDebug.html.twig', id: 'ngmore_legacy_debug' }

    ngmore.limitation_type.function_list:
        class: %ngmore.limitation_type.function_list.class%
        arguments: [@ezpublish.api.persistence_handler]
        tags:
            - {name: ezpublish.limitationType, alias: FunctionList}

    ngmore.legacy_mapper.configuration:
        class: %ngmore.legacy_mapper.configuration.class%
        arguments:
            - @ezpublish.config.resolver.core
            - %ngmore.legacy_mapper.configuration.options%
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: kernel.event_subscriber }
