parameters:
    twig.extension.text.class: Twig_Extensions_Extension_Text
    twig.extension.array.class: Twig_Extensions_Extension_Array
    twig.extension.date.class: Twig_Extensions_Extension_Date

    ngmore.templating.converter.user.class: Netgen\Bundle\MoreBundle\Templating\Converter\UserConverter
    ngmore.templating.global_helper.class: Netgen\Bundle\MoreBundle\Templating\GlobalHelper
    ngmore.templating.twig.extension.class: Netgen\Bundle\MoreBundle\Templating\Twig\Extension\NetgenMoreExtension

services:
    twig.extension.text:
        class: %twig.extension.text.class%
        tags:
            - { name: twig.extension }

    twig.extension.array:
        class: %twig.extension.array.class%
        tags:
            - { name: twig.extension }

    twig.extension.date:
        class: %twig.extension.date.class%
        tags:
            - { name: twig.extension }

    ngmore.templating.converter.user:
        class: %ngmore.templating.converter.user.class%
        arguments:
            - "@ezpublish_legacy.kernel"
        tags:
            - {name: ezpublish_legacy.templating.converter, for: eZ\Publish\Core\Repository\Values\User\User}

    ngmore.templating.global_helper:
        class: %ngmore.templating.global_helper.class%
        arguments:
            - "@ngmore.helper.site_info_helper"
            - "@ngmore.helper.layout_helper"
            - "@request_stack"

    ngmore.templating.twig.extension:
        class: %ngmore.templating.twig.extension.class%
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.translation_helper"
            - "@ngmore.helper.path_helper"
            - "@ngmore.templating.global_helper"
            - "@ezpublish.locale.converter"
        tags:
            - { name: twig.extension }
