parameters:
    twig.extension.text.class: Twig_Extensions_Extension_Text
    twig.extension.array.class: Twig_Extensions_Extension_Array
    twig.extension.date.class: Twig_Extensions_Extension_Date

    netgen_more.templating.converter.user.class: Netgen\Bundle\MoreBundle\Templating\Converter\UserConverter
    netgen_more.templating.global_helper.class: Netgen\Bundle\MoreBundle\Templating\GlobalHelper
    netgen_more.templating.twig.extension.class: Netgen\Bundle\MoreBundle\Templating\Twig\Extension\NetgenMoreExtension

services:
    twig.extension.text:
        class: %twig.extension.text.class%
        tags:
            - { name: twig.extension }

    twig.extension.array:
        class: %twig.extension.array.class%
        tags:
            - { name: twig.extension }

    twig.extension.date:
        class: %twig.extension.date.class%
        tags:
            - { name: twig.extension }

    netgen_more.templating.converter.user:
        class: %netgen_more.templating.converter.user.class%
        arguments:
            - @ezpublish_legacy.kernel
        tags:
            - {name: ezpublish_legacy.templating.converter, for: eZ\Publish\Core\Repository\Values\User\User}

    netgen_more.templating.global_helper:
        class: %netgen_more.templating.global_helper.class%
        arguments:
            - @netgen_more.helper.site_info_helper
            - @netgen_more.helper.layout_helper
            - @ezpublish.config.resolver
        calls:
            - [setRequest, [@?request=]]

    netgen_more.templating.twig.extension:
        class: %netgen_more.templating.twig.extension.class%
        arguments:
            - @ezpublish.api.repository
            - @netgen_more.helper.path_helper
            - @netgen_more.templating.global_helper
            - @ezpublish.locale.converter
        tags:
            - { name: twig.extension }
