Netgen\Bundle\SiteBundle\Entity\EzUserAccountKey:
    type: entity
    repositoryClass: Netgen\Bundle\SiteBundle\Entity\Repository\EzUserAccountKeyRepository
    table: ezuser_accountkey
    id:
        id:
            type: integer
            column: id
            id: true
            generator: { strategy: AUTO }
    fields:
        hashKey:
            type: string
            length: 32
            options:
                default: ""
            column: hash_key
        time:
            type: integer
            options:
                default: 0
            column: time
        userId:
            type: integer
            options:
                default: 0
            column: user_id
    indexes:
        hash_key:
            columns: [hash_key]
