services:
    _defaults:
        autoconfigure: true

    ngsite.controller.base:
        class: Netgen\Bundle\SiteBundle\Controller\Controller
        parent: netgen.ibexa_site_api.controller.base
        abstract: true
        autoconfigure: false

    ngsite.controller.check_redirect:
        class: Netgen\Bundle\SiteBundle\Controller\CheckRedirect
        parent: ngsite.controller.base
        arguments:
            - "@ngsite.helper.redirect_helper"

    ngsite.controller.embed_view.image:
        class: Netgen\Bundle\SiteBundle\Controller\EmbedView\Image
        parent: ngsite.controller.base
        arguments:
            - "@netgen.ibexa_site_api.site"
            - "@?logger"

    ngsite.controller.search:
        class: Netgen\Bundle\SiteBundle\Controller\Search
        parent: ngsite.controller.base
        arguments:
            - "@netgen.ibexa_site_api.site"
            - "@Ibexa\\Core\\QueryType\\ArrayQueryTypeRegistry"
            - "@ibexa.config.resolver"
            - "@ngsite.search.resolver.suggestion"

    ngsite.controller.menu:
        class: Netgen\Bundle\SiteBundle\Controller\Menu
        parent: ngsite.controller.base
        arguments:
            - "@knp_menu.menu_provider"
            - "@knp_menu.renderer_provider"
            - "@ibexa.config.resolver"
            - "@fos_http_cache.http.symfony_response_tagger"

    ngsite.controller.relations.related_items:
        class: Netgen\Bundle\SiteBundle\Controller\Relations\RelatedItems
        parent: ngsite.controller.base
        arguments:
            - "@ngsite.relation.location_resolver"

    ngsite.controller.relations.related_multimedia_items:
        class: Netgen\Bundle\SiteBundle\Controller\Relations\RelatedMultimediaItems
        parent: ngsite.controller.base
        arguments:
            - "@ngsite.relation.multimedia_resolver"

    ngsite.controller.download:
        class: Netgen\Bundle\SiteBundle\Controller\Download
        parent: ngsite.controller.base
        arguments:
            - "@netgen.ibexa_site_api.site"
            - "@ibexa.field_type.ezbinaryfile.io_service"
            - "@ibexa.field_type.ezimage.io_service.published"
            - "@translator"
            - "@event_dispatcher"

    ngsite.controller.user.register:
        class: Netgen\Bundle\SiteBundle\Controller\User\Register
        parent: ngsite.controller.base
        arguments:
            - "@ibexa.api.service.user"
            - "@ibexa.api.service.content_type"
            - "@event_dispatcher"
            - "@ibexa.api.repository"
            - "@ibexa.config.resolver"

    ngsite.controller.user.activation_form:
        class: Netgen\Bundle\SiteBundle\Controller\User\ActivationForm
        parent: ngsite.controller.base
        arguments:
            - "@ibexa.api.service.user"
            - "@event_dispatcher"
            - "@ibexa.config.resolver"

    ngsite.controller.user.activate:
        class: Netgen\Bundle\SiteBundle\Controller\User\Activate
        parent: ngsite.controller.base
        arguments:
            - "@ibexa.api.service.user"
            - "@event_dispatcher"
            - "@ngsite.repository.user_accountkey"
            - "@ibexa.api.repository"
            - "@ibexa.config.resolver"

    ngsite.controller.user.forgot_password:
        class: Netgen\Bundle\SiteBundle\Controller\User\ForgotPassword
        parent: ngsite.controller.base
        arguments:
            - "@ibexa.api.service.user"
            - "@event_dispatcher"
            - "@ibexa.config.resolver"

    ngsite.controller.user.reset_password:
        class: Netgen\Bundle\SiteBundle\Controller\User\ResetPassword
        parent: ngsite.controller.base
        arguments:
            - "@ibexa.api.service.user"
            - "@event_dispatcher"
            - "@ngsite.repository.user_accountkey"
            - "@ibexa.api.repository"
            - "@ibexa.config.resolver"

    ngsite.controller.view_modal:
        class: Netgen\Bundle\SiteBundle\Controller\ViewModal
        parent: ngsite.controller.base

    ngsite.controller.info_collection.ajax_submit:
        class: Netgen\Bundle\SiteBundle\Controller\InfoCollection\AjaxSubmit
        parent: ngsite.controller.base

    ngsite.controller.info_collection.view_modal:
        class: Netgen\Bundle\SiteBundle\Controller\InfoCollection\ViewModal
        parent: ngsite.controller.base
        arguments:
            - "@ngsite.info_collection.referer_resolver"

    ngsite.controller.info_collection.proxy_form_handler:
        class: Netgen\Bundle\SiteBundle\Controller\InfoCollection\ProxyFormHandler
        parent: ngsite.controller.base
        arguments:
            - "@request_stack"
            - "@netgen_information_collection.captcha.service"
            - "@netgen_information_collection.handler"
            - "@event_dispatcher"
            - "@ngsite.info_collection.referer_resolver"
            - "@?logger"
