system:
    default:
        field_templates:
            - { template: "@NetgenSite/parts/content_fields.html.twig", priority: 5000 }
    admin_group:
        fieldtypes:
            ezrichtext:
                custom_tags: [video, factbox, quote]
                toolbars:
                    ezadd:
                        buttons:
                            video:
                                priority: 3
                            factbox:
                                priority: 2
                            quote:
                                priority: 1
                    video:
                        buttons:
                            ezmoveup:
                                priority: 40
                            ezmovedown:
                                priority: 30
                            ezcustomtagedit:
                                priority: 20
                            ezblockremove:
                                priority: 10
                    factbox:
                        buttons:
                            ezmoveup:
                                priority: 40
                            ezmovedown:
                                priority: 30
                            ezcustomtagedit:
                                priority: 20
                            ezblockremove:
                                priority: 10
                    quote:
                        buttons:
                            ezmoveup:
                                priority: 40
                            ezmovedown:
                                priority: 30
                            ezcustomtagedit:
                                priority: 20
                            ezblockremove:
                                priority: 10
