services:
    ngsite.field_type.ezrichtext.converter.direct_download:
        class: Netgen\Bundle\SiteBundle\RichText\Converter\EzLinkDirectDownload
        arguments:
            - "@netgen.ezplatform_site.load_service"
            - "@router"
            - "@?logger"
        tags:
            - { name: ezrichtext.converter.output.xhtml5, priority: -10 }
