services:
    ngsite.field_type.ezxmltext.converter.direct_download:
        class: Netgen\Bundle\SiteBundle\XmlText\Converter\EzLinkDirectDownload
        public: false
        arguments:
            - "@netgen.ezplatform_site.load_service"
            - "@router"
            - "@?logger"
        tags:
            - { name: ezpublish.ezxml.converter }
