system:
    default:
        field_templates:
            - { template: "@NetgenSite/parts/content_fields.html.twig", priority: 5000 }
        ng_site_api:
            named_objects:
                locations:
                    site_info: '%ngsite.default.locations.site_info.id%'
    admin_group:
        fieldtypes:
            ezrichtext:
                classes:
                    table:
                        choices:
                            - regular
                            - table-bordered
                            - table-striped
                            - table-hover
                            - table-condensed
                            - table-no-skin
                        default_value: regular
                        required: false
                        multiple: false
                    ezlink:
                        choices:
                            - none
                            - btn-default
                            - btn-primary
                        default_value: none
                        required: false
                        multiple: false
                attributes:
                    table:
                        caption:
                            type: string
                            required: false
                        responsive:
                            type: boolean
                            default_value: false
                    ezlink:
                        link-suffix:
                            type: string
                            required: false
                        direct-download:
                            type: boolean
                            default_value: false
                        open-inline:
                            type: boolean
                            default_value: false
                custom_tags:
                    - video
                    - factbox
                    - quote
                toolbar:
                    custom_tags_group:
                        buttons:
                            video:
                                priority: 60
                            factbox:
                                priority: 50
                            quote:
                                priority: 40
