services:
    ngsite.menu.relation_list_menu_builder:
        class: Netgen\Bundle\SiteBundle\Menu\RelationListMenuBuilder
        arguments:
            - "@ngsite.menu.factory.location"
            - "@netgen.ezplatform_site.load_service"
            - "@ngsite.helper.site_info_helper"
            - "@?logger"
        tags:
            - { name: monolog.logger, channel: ngsite }

    ngsite.menu.voter.location_path:
        class: Netgen\Bundle\SiteBundle\Menu\Voter\LocationPathVoter
        arguments:
            - "@request_stack"
        tags:
            - { name: knp_menu.voter }

    ngsite.menu.factory.location:
        class: Netgen\Bundle\SiteBundle\Menu\Factory\LocationFactory
        arguments:
            - "@event_dispatcher"
            - "@ngsite.menu.factory.location.extension.fallback"
            - []

    ngsite.menu.factory.location.extension.fallback:
        class: Netgen\Bundle\SiteBundle\Menu\Factory\LocationFactory\FallbackExtension
        arguments:
            - "@router"

    ngsite.menu.factory.location.extension.shortcut:
        class: Netgen\Bundle\SiteBundle\Menu\Factory\LocationFactory\ShortcutExtension
        arguments:
            - "@netgen.ezplatform_site.load_service"
            - "@router"
            - "@request_stack"
            - "@?logger"
        tags:
            - { name: ngsite.menu.factory.location.extension, priority: 0 }
            - { name: monolog.logger, channel: ngsite }

    ngsite.menu.factory.location.extension.menu_item:
        class: Netgen\Bundle\SiteBundle\Menu\Factory\LocationFactory\MenuItemExtension
        arguments:
            - "@netgen.ezplatform_site.load_service"
            - "@netgen.ezplatform_site.filter_service"
            - "@router"
            - "@request_stack"
            - "@ezpublish.config.resolver"
            - "@?logger"
        tags:
            - { name: ngsite.menu.factory.location.extension, priority: 0 }
            - { name: monolog.logger, channel: ngsite }

    ngsite.menu.main_menu:
        class: Knp\Menu\MenuItem
        factory: ["@ngsite.menu.relation_list_menu_builder", createRelationListMenu]
        arguments:
            - main_menu
        tags:
            - { name: knp_menu.menu, alias: ngsite_main_menu }

    ngsite.menu.additional_menu:
        class: Knp\Menu\MenuItem
        factory: ["@ngsite.menu.relation_list_menu_builder", createRelationListMenu]
        arguments:
            - additional_menu
        tags:
            - { name: knp_menu.menu, alias: ngsite_additional_menu }
