services:
    ngsite.pagerfanta.view.site:
        class: Netgen\Bundle\SiteBundle\Pagerfanta\View\SiteView
        public: false
        arguments:
            - "@twig"
        calls:
            - [setDefaultTemplate, [$template.pagerfanta.ngsite;ngsite$]]
        tags:
            - { name: pagerfanta.view, alias: ngsite }
