parameters:
    ngsite.default.locale.conversion_map: "%ibexa.locale.conversion_map%"

    ngsite.default.site_domain: localhost

    ngsite.default.locations.site_info.id: ~

    ngsite.default.google_maps.latitude: 45.79849
    ngsite.default.google_maps.longitude: 15.90777
    ngsite.default.google_maps.zoom: 13
    # Valid options for map type are ROADMAP, SATELLITE, HYBRID, TERRAIN
    ngsite.default.google_maps.map_type: ROADMAP

    ngsite.default.site_settings.google_analytics_code: ~
    ngsite.default.site_settings.google_analytics_universal: true
    ngsite.default.site_settings.google_tag_manager_code: ~
    ngsite.default.site_settings.add_this_code: ~
    ngsite.default.site_settings.typekit_code: ~
    ngsite.default.site_settings.facebook_api: false
    ngsite.default.site_settings.facebook_locale: en_US
    ngsite.default.site_settings.jwplayer_id: 'gYe8hbFO'
    ngsite.default.site_settings.jwplayer_key: ~
    ngsite.default.site_settings.meta_data: []
    ngsite.default.site_settings.show_path_in_title: false

    ngsite.default.path_helper.excluded_content_types: ['ng_container', 'folder']
    ngsite.default.container_content_types: ['ng_container', 'folder']

    ngsite.default.set_creation_date.enabled: false
    ngsite.default.set_creation_date.fields:
        ng_news: publish_date
        ng_blog_post: publish_date

    ngsite.default.mail.sender_email: 'info@example.com'
    ngsite.default.mail.sender_name: 'Netgen Site'
    ngsite.default.mail.admin_email: ~
    ngsite.default.mail.admin_name: ~

    ngsite.default.newsletter.sender_email: 'test@netgen.io'
    ngsite.default.newsletter.recipient_email: 'test@netgen.io'

    ngsite.default.info_collection.mailer_lite.api_key: '%env(MAILER_LITE_API_KEY)%'

    ngsite.default.user.content_type_identifier: 'user'
    ngsite.default.user.user_group_content_id: 11
    ngsite.default.user.auto_enable: false
    ngsite.default.user.require_admin_activation: false
    ngsite.default.user.activate_hash_validity_time: 3600
    ngsite.default.user.forgot_password_hash_validity_time: 3600
    ngsite.default.user.mail.admin_email: "%ngsite.default.mail.admin_email%"
    ngsite.default.user.mail.admin_name: "%ngsite.default.mail.admin_name%"

    ngsite.default.view.shared_max_age: 86400

    ngsite.default.search.default_limit: 10
    ngsite.default.search.content_types: []

    ngsite.default.template.errors.default: '@@NetgenSite/errors/default.html.twig'
    ngsite.default.template.pagerfanta.ngsite: '@@NetgenSite/pagerfanta/ngsite.html.twig'
    ngsite.default.template.search: '@@NetgenSite/search/search.html.twig'
    ngsite.default.template.menu: '@@KnpMenu/menu.html.twig'
    
    # specify all mime types for which download links should do inline representation and not download the file automatically
    ngsite.default.download.show_inline:
        - 'application/pdf'

    ngsite.phpstorm_twig_integration.enabled: '%kernel.debug%'

    ngsite.default.direct_download.content_types:
        - file
