ngsite_download:
    path: /content/download/{contentId}/{fieldId}/{isInline}
    controller: ngsite.controller.download
    methods: [GET]
    requirements:
        contentId: '\d+'
        fieldId: '\d+'
        isInline: 0|1
    defaults:
        isInline: 0

ngsite_user_register:
    path: /user/register
    controller: ngsite.controller.user.register

ngsite_resend_activation_mail:
    path: /user/activate
    controller: ngsite.controller.user.activation_form

ngsite_user_activate:
    path: /user/activate/{hash}
    controller: ngsite.controller.user.activate

ngsite_user_forgot_password:
    path: /user/forgotpassword
    controller: ngsite.controller.user.forgot_password

ngsite_user_reset_password:
    path: /user/forgotpassword/{hash}
    controller: ngsite.controller.user.reset_password

ngsite_content_search:
    path: /content/search
    controller: ngsite.controller.search

# Rewire eZ Platform built in routes to Netgen variants

ezplatform.user.register:
    path: /user/register
    controller: ngsite.controller.user.register

ezplatform.user.user_register:
    path: /user/register
    controller: ngsite.controller.user.register

# Disable eZ Platform built in routes

ezplatform.user.register_confirmation:
    path: /_error/404

ez_content_download:
    path: /_error/404

ez_content_download_field_id:
    path: /_error/404

ez_user_register:
    path: /_error/404

ezplatform.user.register:
    path: /_error/404

ezplatform.user.user_register:
    path: /_error/404

ez_user_register_confirmation:
    path: /_error/404

ezplatform.user.register_confirmation:
    path: /_error/404

ezplatform.user.user_register_confirmation:
    path: /_error/404
