services:
    ngsite.command.generate_image_variations:
        class: Netgen\Bundle\SiteBundle\Command\GenerateImageVariationsCommand
        public: false
        arguments:
            - "@ezpublish.api.repository"
            - "@ezpublish.fieldType.ezimage.variation_service"
            - "@ezpublish.cache_pool"
            - "@ezpublish.config.resolver"
        tags:
            - { name: console.command, command: 'ngsite:content:generate-image-variations' }

    ngsite.command.profiler_cache_purger:
        class: Netgen\Bundle\SiteBundle\Command\ProfilerCachePurgerCommand
        public: false
        arguments:
            - "@?profiler"
        tags:
            - { name: console.command, command: 'ngsite:profiler:clear-cache' }

    ngsite.controller.base:
        class: Netgen\Bundle\SiteBundle\Controller\Controller
        parent: netgen.ezplatform_site.controller.base
        public: false
        abstract: true

    ngsite.controller.redirect:
        class: Netgen\Bundle\SiteBundle\Controller\RedirectController
        public: true
        parent: ngsite.controller.base
        arguments:
            - "@router"

    ngsite.controller.embed_view:
        class: Netgen\Bundle\SiteBundle\Controller\EmbedViewController
        public: true
        parent: ngsite.controller.base
        arguments:
            - "@router"
            - "@?logger"

    ngsite.controller.search:
        class: Netgen\Bundle\SiteBundle\Controller\SearchController
        public: true
        parent: ngsite.controller.base
        arguments:
            - "@ngsite.search.resolver.suggestion"

    ngsite.controller.menu:
        class: Netgen\Bundle\SiteBundle\Controller\MenuController
        public: true
        parent: ngsite.controller.base
        arguments:
            - "@knp_menu.menu_provider"
            - "@knp_menu.renderer_provider"
            - "@fos_http_cache.handler.tag_handler"

    ngsite.controller.parts:
        class: Netgen\Bundle\SiteBundle\Controller\PartsController
        public: true
        parent: ngsite.controller.base
        arguments:
            - "@ngsite.relation.location_resolver"
            - "@ngsite.relation.multimedia_resolver"

    ngsite.controller.download:
        class: Netgen\Bundle\SiteBundle\Controller\DownloadController
        public: true
        parent: ngsite.controller.base
        arguments:
            - "@ezpublish.fieldType.ezbinaryfile.io_service"
            - "@ezpublish.fieldType.ezimage.io_service"
            - "@translator"
            - "@event_dispatcher"

    ngsite.controller.user:
        class: Netgen\Bundle\SiteBundle\Controller\UserController
        public: true
        parent: ngsite.controller.base
        arguments:
            - "@ezpublish.api.service.user"
            - "@event_dispatcher"
            - "@form.factory"
            - "@ngsite.repository.ezuser_accountkey"

    ngsite.param_converter.content:
        class: Netgen\Bundle\SiteBundle\ParamConverter\ContentParamConverter
        public: false
        arguments:
            - "@netgen.ezplatform_site.load_service"
        tags:
            - { name: request.param_converter, priority: 100 }

    ngsite.param_converter.location:
        class: Netgen\Bundle\SiteBundle\ParamConverter\LocationParamConverter
        public: false
        arguments:
            - "@netgen.ezplatform_site.load_service"
        tags:
            - { name: request.param_converter, priority: 100 }

    ngsite.relation.location_resolver:
        class: Netgen\Bundle\SiteBundle\Relation\LocationRelationResolver
        public: false
        arguments:
            - "@netgen.ezplatform_site.load_service"
            - "@?logger"
        tags:
            - { name: monolog.logger, channel: ngsite }

    ngsite.relation.multimedia_resolver:
        class: Netgen\Bundle\SiteBundle\Relation\MultimediaRelationResolver
        public: false
        arguments:
            - "@netgen.ezplatform_site.load_service"
            - "@ngsite.relation.location_resolver"

    ngsite.helper.path_helper:
        class: Netgen\Bundle\SiteBundle\Helper\PathHelper
        public: false
        arguments:
            - "@netgen.ezplatform_site.load_service"
            - "@ezpublish.config.resolver"
            - "@router"

    ngsite.helper.site_info_helper:
        class: Netgen\Bundle\SiteBundle\Helper\SiteInfoHelper
        public: false
        arguments:
            - "@netgen.ezplatform_site.load_service"
            - "@ezpublish.config.resolver"

    ngsite.helper.mail_helper:
        class: Netgen\Bundle\SiteBundle\Helper\MailHelper
        public: false
        arguments:
            - "@mailer"
            - "@twig"
            - "@router"
            - "@translator"
            - "@ezpublish.config.resolver"
            - "@ngsite.helper.site_info_helper"
            - "@?logger"

    ngsite.helper.redirect_helper:
        class: Netgen\Bundle\SiteBundle\Helper\RedirectHelper
        public: false
        arguments:
            - "@router"

    ngsite.repository.nguser_setting:
        class: Doctrine\ORM\EntityRepository
        public: false
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - Netgen\Bundle\SiteBundle\Entity\NgUserSetting

    ngsite.repository.ezuser_accountkey:
        class: Doctrine\ORM\EntityRepository
        public: false
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - Netgen\Bundle\SiteBundle\Entity\EzUserAccountKey

    ngsite.slot.create_user:
        class: Netgen\Bundle\SiteBundle\Core\Slot\CreateUserSlot
        public: false
        arguments:
            - "@ezpublish.api.service.user"
            - "@ngsite.repository.nguser_setting"
        tags:
            - { name: ezpublish.api.slot, signal: UserService\CreateUserSignal }

    ngsite.routing.site_content_url_alias_router:
        class: Netgen\Bundle\SiteBundle\Routing\SiteContentUrlAliasRouter
        public: false
        arguments:
            - "@ezpublish.urlalias_generator"
            - "@?router.request_context"
        tags:
            - { name: router, priority: 200 }

    ngsite.routing.site_location_url_alias_router:
        class: Netgen\Bundle\SiteBundle\Routing\SiteLocationUrlAliasRouter
        public: false
        arguments:
            - "@ezpublish.urlalias_generator"
            - "@?router.request_context"
        tags:
            - { name: router, priority: 200 }

    ngsite.opengraph.handler.site_name:
        class: Netgen\Bundle\SiteBundle\OpenGraph\Handler\SiteName
        public: false
        arguments:
            - "@ngsite.helper.site_info_helper"
        tags:
            - { name: netgen_open_graph.meta_tag_handler, alias: ngsite/site_name }

    ngsite.opengraph.handler.site_image:
        class: Netgen\Bundle\SiteBundle\OpenGraph\Handler\SiteImage
        public: false
        arguments:
            - "@ngsite.helper.site_info_helper"
            - "@request_stack"
        tags:
            - { name: netgen_open_graph.meta_tag_handler, alias: ngsite/site_image }

    ngsite.query_type.search:
        class: Netgen\Bundle\SiteBundle\QueryType\SearchQueryType
        public: false
        arguments:
            - "@netgen.ezplatform_site.site"
            - "@ezpublish.config.resolver"
        tags:
            - { name: ezpublish.query_type }

    ngsite.topic.url_generator:
        class: Netgen\Bundle\SiteBundle\Topic\UrlGenerator
        public: false
        arguments:
            - "@netgen.ezplatform_site.find_service"
            - "@netgen.ezplatform_site.load_service"
            - "@ezpublish.config.resolver"
            - "@router"

    ngsite.search.resolver.suggestion:
        class: Netgen\Bundle\SiteBundle\Core\Search\SuggestionResolver
        public: false

#    Custom user context hash providers are disabled by default.
#    Enable them in your project if needed by copying one of the
#    following service definitions.
#
#    ngsite.context_provider.session:
#        class: Netgen\Bundle\SiteBundle\ContextProvider\SessionContextProvider
#        public: false
#        arguments:
#            - "@session"
#    tags:
#        - { name: fos_http_cache.user_context_provider }
#
#    ngsite.context_provider.user:
#        class: Netgen\Bundle\SiteBundle\ContextProvider\UserContextProvider
#        public: false
#        arguments:
#            - "@ezpublish.api.repository"
#    tags:
#        - { name: fos_http_cache.user_context_provider }
