parameters:
    netgen_block_manager.block.block_definition.handler.background_color.colors:
        white: 'block.plugin.background_color.white'
        black: 'block.plugin.background_color.black'

services:
    ngmore.layouts.block.plugin.vertical_whitespace:
        class: Netgen\Bundle\MoreBundle\Layouts\Block\Plugin\VerticalWhitespacePlugin
        public: false
        tags:
            - { name: netgen_block_manager.block.block_definition_handler.plugin, priority: 200 }

    ngmore.layouts.block.plugin.background_image:
        class: Netgen\Bundle\MoreBundle\Layouts\Block\Plugin\BackgroundImagePlugin
        public: false
        arguments:
            - "@netgen.ezplatform_site.load_service"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler.plugin, priority: 300 }

    ngmore.layouts.block.plugin.background_color:
        class: Netgen\Bundle\MoreBundle\Layouts\Block\Plugin\BackgroundColorPlugin
        public: false
        arguments:
            - "%netgen_block_manager.block.block_definition.handler.background_color.colors%"
        tags:
            - { name: netgen_block_manager.block.block_definition_handler.plugin, priority: 400 }

    ngmore.layouts.block.plugin.set_container:
        class: Netgen\Bundle\MoreBundle\Layouts\Block\Plugin\SetContainerPlugin
        public: false
        tags:
            - { name: netgen_block_manager.block.block_definition_handler.plugin, priority: -100 }
