services:
    ngsite.opengraph.handler.image:
        class: Netgen\Bundle\SiteBundle\OpenGraph\Handler\Image
        public: false
        arguments:
            - "@ezpublish.field_helper"
            - "@ezpublish.translation_helper"
            - "@netgen_open_graph.handler.field_type.image"
            - "@netgen_remote_media.open_graph_handler"
        tags:
            - { name: netgen_open_graph.meta_tag_handler, alias: ngsite/image }

    ngsite.templating.twig.extension.remote_media:
        class: Netgen\Bundle\SiteBundle\Templating\Twig\Extension\RemoteMediaExtension
        public: false
        tags:
            - { name: twig.extension }

    ngsite.templating.twig.runtime.remote_media:
        class: Netgen\Bundle\SiteBundle\Templating\Twig\Extension\RemoteMediaRuntime
        public: false
        arguments:
            - "@ezpublish.fieldType.ezimage.variation_service"
            - "@netgen_remote_media.provider"
        tags:
            - { name: twig.runtime }
